spring.application.name=ProfileMS

server.port=9100
spring.datasource.url=jdbc:postgresql://localhost:5432/hms_profile_db
spring.datasource.username=postgres
spring.datasource.password=aman

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
DOCTOR_NOT_FOUND=Doctor not found
DOCTOR_ALREADY_EXISTS=Doctor already exists

PATIENT_NOT_FOUND=Patient not found
PATIENT_ALREADY_EXISTS=Patient already exists


spring.output.ansi.enabled=always
