spring.application.name=PharmacyMS
server.port=9300

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/hms_pharmacy_db
spring.datasource.username=postgres
spring.datasource.password=admin123
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Spring Boot Actuator
management.endpoint.web.exposure.include=health,info
spring.output.ansi.enabled=always

MEDICINE_ALREADY_EXISTS=Medicine already exists.
MEDICINE_NOT_FOUND=Medicine not found.
SALES_ALREADY_EXISTS=Sales record already exists.
SALE_NOT_FOUND=Sale not found.
INVENTORY_NOT_FOUND=Inventory not found.
OUT_OF_STOCK=Medicine is out of stock.
INSUFFICIENT_STOCK=Insufficient stock available.
