import exec from 'k6/execution';
import { uniqueSignupEmail } from './helpers.js';

const RUN_ID = __ENV.RUN_ID || `${Date.now()}`;

export function signupPayload() {
  return {
    email: uniqueSignupEmail(),
    password: 'Password@123',
    name: 'Load Test User',
    role: 'PATIENT',
  };
}

export function loginPayload(email) {
  return { email, password: 'Password@123' };
}

export function appointmentSchedulePayload(doctorProfileId, patientProfileId, sequence) {
  return {
    doctorId: doctorProfileId,
    patientId: patientProfileId,
    appointmentTime: futureLocalDateTime(sequence === undefined ? exec.scenario.iterationInTest : sequence, 1),
    reason: 'Load test visit',
    notes: 'Generated by k6 load test',
  };
}

export function medicinePayload(id, sequence) {
  const n = sequence === undefined ? exec.scenario.iterationInTest : sequence;
  return {
    id,
    name: `K6 Medicine ${RUN_ID} ${n}`,
    dosage: '500mg',
    description: 'Generated by k6 load test',
    category: 'ANALGESICS',
    type: 'TABLET',
    manufacturer: 'HMS Load Test',
    unitPrice: 25,
    notes: 'Generated by k6 load test',
  };
}

// LocalDateTime expects ISO local datetime, not a UTC timestamp with "Z".
// The sequence makes appointmentTime globally unique across k6 iterations.
function futureLocalDateTime(sequence, daysAhead) {
  const date = new Date();
  date.setDate(date.getDate() + daysAhead);
  date.setSeconds(date.getSeconds() + sequence);
  return date.toISOString().slice(0, 19);
}
