# ===========================
# Docker Profile - GatewayMS
# ===========================
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka

# Allow frontend container or host to access gateway
spring.cloud.gateway.server.webflux.globalcors.cors-configurations[/**].allowedOrigins=${FRONTEND_URL:http://localhost:5173}
