spring.application.name=AppointmentMS
server.port=9200
spring.datasource.url=jdbc:postgresql://localhost:5432/appointmentdb
spring.datasource.username=root
spring.datasource.password=aman

# color config 
spring.output.ansi.enabled=always


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#eureka.instance.instance-id=${spring.application.name}:${random.value}

APPOINTMENT_NOT_FOUND=Appointment not found
APPOINTMENT_ALREADY_CANCELLED=Appointmentalready cancelled

DOCTOR_NOT_FOUND=Doctor not found
PATIENT_NOT_FOUND=Patient not found