spring.application.name=AppointmentMS
server.port=9200

spring.datasource.url=jdbc:postgresql://localhost:5432/hms_appointment_db
spring.datasource.username=postgres
spring.datasource.password=admin123
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# color config 
spring.output.ansi.enabled=always


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#eureka.instance.instance-id=${spring.application.name}:${random.value}

APPOINTMENT_NOT_FOUND=Appointment not found
APPOINTMENT_ALREADY_CANCELLED=Appointment already cancelled

DOCTOR_NOT_FOUND=Doctor not found
PATIENT_NOT_FOUND=Patient not found

APPOINTMENT_RECORD_NOT_FOUND=Appointment record not found
APPOINTMENT_RECORD_ALREADY_EXISTS=Appointment record already exists

PRESCRIPTION_NOT_FOUND=Prescription not found

DOCTOR_ALREADY_HAVE_APPOINTMENT_AT_THIS_TIME=Doctor already has an appointment at this time.
PATIENT_ALREADY_HAVE_APPOINTMENT_AT_THIS_TIME=Patient already has an appointment at this time.
APPOINTMENT_TIME_IS_IN_PAST=Appointment time cannot be in the past.
CANNOT_CANCEL_APPOINTMENT_TIME_IS_IN_PAST=Cannot cancel appointment as the time is in the past.
ONLY_SCHEDULED_CAN_BE_COMPLETED=Only scheduled appointments can be marked as completed.
CANNOT_COMPLETE_FUTURE_APPOINTMENT=Cannot complete a future appointment.
ONLY_SCHEDULED_CAN_BE_RESCHEDULED=Only scheduled appointments can be rescheduled.
CANNOT_RESCHEDULE_TO_PAST_DATE=Cannot reschedule to a past date.
DOCTOR_NOT_AVAILABLE_AT_THIS_TIME=Doctor is not available at this time.


# Kafka
#  This means our kafka server is running on localhost:9092
spring.kafka.bootstrap-servers=localhost:9092
# These two means how to produce data to kafka
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# These two means how to consume data from kafka
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
# This means only allow Event class from this package to be deserialized
spring.kafka.consumer.properties.spring.json.trusted.packages=com.hms.appointment.event

hms.kafka.topic.appointment=hms.appointment-events