# ===========================
# Docker Profile - UserMS
# ===========================
spring.datasource.url=jdbc:postgresql://postgres:5432/hms_user_db
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
