# ===========================
# Docker Profile - NotificationMS
# ===========================
spring.datasource.url=jdbc:postgresql://postgres:5432/hms_notification_db
spring.kafka.bootstrap-servers=kafka:29092
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
