package com.hms.testtools.generator;

import com.hms.testtools.dto.MedicineCategory;
import com.hms.testtools.dto.MedicineType;
import com.hms.testtools.dto.Medicines;
import com.hms.testtools.dto.PharmacyMedicineDTO;
import net.datafaker.Faker;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import java.time.LocalDateTime;

@Component
public class MedicineGenerator {

    @Autowired
    private Faker faker;

    public PharmacyMedicineDTO generateMedicine() {
        PharmacyMedicineDTO med = new PharmacyMedicineDTO();
        Medicines predefinedMed = faker.options().option(Medicines.values());
        
        med.setName(predefinedMed.getName());
        med.setDescription("Generated description for " + predefinedMed.getName());
        med.setDosage(predefinedMed.getDosage());
        med.setCategory(predefinedMed.getCategory());
        med.setType(predefinedMed.getType());
        med.setManufacturer(faker.company().name());
        med.setUnitPrice(faker.number().numberBetween(5, 500));
        med.setStock(0);
        med.setMfd(LocalDateTime.now().minusMonths(faker.number().numberBetween(1, 6)));
        med.setExpDate(LocalDateTime.now().plusYears(faker.number().numberBetween(1, 3)));
        med.setNotes("Generated by generator");
        med.setCreatedAt(LocalDateTime.now());
        return med;
    }
}
