spring.application.name=HMSTestSuite
server.port=8085
gateway.url=http://localhost:9000

# Seeder performance parameters
performance.doctors=1500
performance.patients=1500
performance.doctorStartIndex=1
performance.patientStartIndex=1
performance.medicines=50
performance.inventoryBatches=50
performance.parallelThreads=30
performance.admins=1
seeder.enabled=true
seeder.parallel=true


