spring.application.name=HMSTestSuite
server.port=8085
gateway.url=http://localhost:9000

# Seeder performance parameters
performance.doctors=500
performance.patients=500
performance.medicines=40
performance.inventoryBatches=50
performance.parallelThreads=20
performance.admins=1
seeder.enabled=true
seeder.parallel=true


