package com.hms.testtools.seeder;

import com.hms.testtools.client.AppointmentClient;
import com.hms.testtools.dto.AppointmentDTO;
import com.hms.testtools.dto.Status;
import net.datafaker.Faker;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import java.time.LocalDateTime;
import java.time.LocalDate;

@Service
public class AppointmentSeeder {

    @Autowired
    private AppointmentClient appointmentClient;

    @Autowired
    private Faker faker;

    public void seedAppointment(Long patientId, Long doctorId) {
        AppointmentDTO appt = new AppointmentDTO();
        appt.setPatientId(patientId);
        appt.setDoctorId(doctorId);
        
        // Generate realistic business hours (9:00 AM - 5:45 PM) with 15-minute slots
        int dayOffset = faker.number().numberBetween(1, 14);
        int hour = faker.number().numberBetween(9, 18); // 9 to 17 inclusive
        int minute = faker.options().option(0, 15, 30, 45);
        LocalDateTime apptTime = LocalDate.now().plusDays(dayOffset).atTime(hour, minute);
        
        appt.setAppointmentTime(apptTime);
        appt.setStatus(Status.SCHEDULED);
        appt.setReason(faker.options().option("Regular Checkup", "Flu Symptoms", "Follow-up", "Consultation"));
        appt.setNotes("Generated by seeder");
        appointmentClient.scheduleAppointment(appt);
    }
}
